In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [ ]:
m = nn.Linear(10, 11, bias=False)

In [ ]:
m.wei

AttributeError: 'Linear' object has no attribute 'wei'

In [ ]:
m.w

AttributeError: 'Linear' object has no attribute 'w'

In [ ]:
m.weight

Parameter containing:
tensor([[-0.2068, -0.2729, -0.2093, -0.3085,  0.2986,  0.0606, -0.3037, -0.2664,
         -0.0694, -0.3155],
        [-0.2376, -0.0515, -0.0405, -0.1154,  0.3017,  0.1733,  0.3135, -0.0158,
         -0.2596, -0.2749],
        [-0.0894,  0.2226,  0.0732,  0.1698, -0.2930,  0.1339,  0.2370, -0.0492,
          0.1766,  0.2702],
        [-0.1604,  0.2836, -0.2424,  0.3041, -0.2746,  0.2549,  0.0266,  0.2767,
          0.0822, -0.2406],
        [ 0.2956, -0.2475,  0.1396, -0.1130, -0.0817, -0.1695, -0.1524,  0.0208,
         -0.1506, -0.0416],
        [-0.1293,  0.0313, -0.1709, -0.1139,  0.2710,  0.2876, -0.2732, -0.0056,
          0.2838,  0.1116],
        [ 0.0426,  0.1459, -0.3114,  0.1077, -0.2822, -0.1166,  0.2798, -0.2950,
         -0.2923,  0.1147],
        [-0.1635,  0.1874, -0.0391, -0.0171, -0.2804,  0.2543, -0.1674, -0.0376,
         -0.0016,  0.1055],
        [ 0.2968,  0.1718,  0.0401, -0.0697, -0.1094, -0.2285, -0.0623, -0.2195,
         -0.0492,  0.1477

In [ ]:
m.to_q.weight.shape

AttributeError: 'Linear' object has no attribute 'to_q'

In [ ]:
m.weight.shape

torch.Size([11, 10])

In [ ]:
x = torch.rand(11, 10)

In [ ]:
m(x)

tensor([[-0.7630, -0.1707,  0.3466,  0.0242, -0.0976, -0.0070,  0.0183, -0.1808,
          0.1524,  0.0366, -0.5014],
        [-0.7951,  0.1422,  0.3333,  0.2267, -0.2692,  0.1445, -0.5855, -0.0402,
         -0.2439,  0.3511, -0.6624],
        [-0.7756, -0.1348,  0.5452,  0.1761, -0.3862,  0.3223, -0.5768,  0.1096,
         -0.1008,  0.4687, -0.6416],
        [-1.0734, -0.0368,  0.5852,  0.2071, -0.3868, -0.0030, -0.3022, -0.2095,
         -0.0719,  0.2796, -0.6966],
        [-0.4774, -0.0599,  0.0047,  0.0714, -0.0501,  0.1714, -0.5700, -0.2942,
         -0.1874, -0.0432, -0.4136],
        [-0.8939, -0.2083,  0.4728,  0.1093, -0.1449,  0.0928, -0.5344,  0.0034,
         -0.0919,  0.3428, -0.5133],
        [-1.0445, -0.1714,  0.6339,  0.5262, -0.4096,  0.0262, -0.1861,  0.1119,
         -0.1492,  0.2443, -0.6779],
        [-0.7613,  0.2788,  0.2472,  0.0650, -0.1931,  0.1634, -0.5555, -0.2222,
         -0.2822,  0.2758, -0.6612],
        [-1.0139, -0.1088,  0.5802,  0.0822, -0.3757,  0

In [ ]:
m(x).shape

torch.Size([11, 11])

In [ ]:
x = torch.ones(11, 10)

In [ ]:
m.weight.shape

torch.Size([11, 10])

In [ ]:
m.weight = torch.one

AttributeError: module 'torch' has no attribute 'one'

In [ ]:
m.weight = torch.ones_like(m.weight)

TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)

In [ ]:
m.weight = nn.Paratorch.ones_like(m.weight)

AttributeError: module 'torch.nn' has no attribute 'Paratorch'

In [ ]:
m.weight = nn.Parameter(torch.ones_like(m.weight))

In [ ]:
m.weight = nn.Parameter(torch.ones_like(m.weight)/10)

In [ ]:
m(x).shape

torch.Size([11, 11])

In [ ]:
m(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], grad_fn=<MmBackward0>)

In [ ]:
import numpy as np

In [ ]:
np.lins

AttributeError: module 'numpy' has no attribute 'lins'

In [ ]:
x = np.linspace(0, 64*10*11, 1)

In [ ]:
x

array([0.])

In [ ]:
x = np.linspace(0, 1, 64*10*11, )

In [ ]:
x

array([0.00000000e+00, 1.42065634e-04, 2.84131269e-04, ...,
       9.99715869e-01, 9.99857934e-01, 1.00000000e+00])

In [ ]:
x = np.linspace(0, 64*10*11)

In [ ]:
x

array([   0.        ,  143.67346939,  287.34693878,  431.02040816,
        574.69387755,  718.36734694,  862.04081633, 1005.71428571,
       1149.3877551 , 1293.06122449, 1436.73469388, 1580.40816327,
       1724.08163265, 1867.75510204, 2011.42857143, 2155.10204082,
       2298.7755102 , 2442.44897959, 2586.12244898, 2729.79591837,
       2873.46938776, 3017.14285714, 3160.81632653, 3304.48979592,
       3448.16326531, 3591.83673469, 3735.51020408, 3879.18367347,
       4022.85714286, 4166.53061224, 4310.20408163, 4453.87755102,
       4597.55102041, 4741.2244898 , 4884.89795918, 5028.57142857,
       5172.24489796, 5315.91836735, 5459.59183673, 5603.26530612,
       5746.93877551, 5890.6122449 , 6034.28571429, 6177.95918367,
       6321.63265306, 6465.30612245, 6608.97959184, 6752.65306122,
       6896.32653061, 7040.        ])

In [ ]:
x.shape

(50,)

In [ ]:
x = np.linspace(0, 64*10*11, 64*10*11, )

In [ ]:
x.shape

(7040,)

In [ ]:
64*11*10

7040

In [ ]:
x

array([0.00000000e+00, 1.00014207e+00, 2.00028413e+00, ...,
       7.03799972e+03, 7.03899986e+03, 7.04000000e+03])

In [ ]:
x = np.linspace(1, 64*10*11, 64*10*11, )

In [ ]:
x

array([1.000e+00, 2.000e+00, 3.000e+00, ..., 7.038e+03, 7.039e+03,
       7.040e+03])

In [ ]:
x.ve

AttributeError: 'numpy.ndarray' object has no attribute 've'

In [ ]:
x = x.view(1, 64, 10, 10)

TypeError: view() takes from 0 to 2 positional arguments but 4 were given

In [ ]:
x = x.view(1, 64, 10, 11)

TypeError: view() takes from 0 to 2 positional arguments but 4 were given

In [ ]:
x = x.reshape(1, 64, 10, 11)

In [ ]:
x

array([[[[1.000e+00, 2.000e+00, 3.000e+00, ..., 9.000e+00, 1.000e+01,
          1.100e+01],
         [1.200e+01, 1.300e+01, 1.400e+01, ..., 2.000e+01, 2.100e+01,
          2.200e+01],
         [2.300e+01, 2.400e+01, 2.500e+01, ..., 3.100e+01, 3.200e+01,
          3.300e+01],
         ...,
         [7.800e+01, 7.900e+01, 8.000e+01, ..., 8.600e+01, 8.700e+01,
          8.800e+01],
         [8.900e+01, 9.000e+01, 9.100e+01, ..., 9.700e+01, 9.800e+01,
          9.900e+01],
         [1.000e+02, 1.010e+02, 1.020e+02, ..., 1.080e+02, 1.090e+02,
          1.100e+02]],

        [[1.110e+02, 1.120e+02, 1.130e+02, ..., 1.190e+02, 1.200e+02,
          1.210e+02],
         [1.220e+02, 1.230e+02, 1.240e+02, ..., 1.300e+02, 1.310e+02,
          1.320e+02],
         [1.330e+02, 1.340e+02, 1.350e+02, ..., 1.410e+02, 1.420e+02,
          1.430e+02],
         ...,
         [1.880e+02, 1.890e+02, 1.900e+02, ..., 1.960e+02, 1.970e+02,
          1.980e+02],
         [1.990e+02, 2.000e+02, 2.010e+02, ..., 2.

In [ ]:
b1, n1, h, w = x.shape

In [ ]:
x1 = x.view(b1, n1, h*w).transpose(1, 2)

TypeError: view() takes from 0 to 2 positional arguments but 3 were given

In [ ]:
x1 = x.reshape(b1, n1, h*w).transpose(1, 2)

ValueError: axes don't match array

In [ ]:
x1 = x.reshape(b1, n1, h*w).transpose(0, 2, 1)

In [ ]:
x1.shape

(1, 110, 64)

In [ ]:
x1.reshape(1, 110, 8, 8)

array([[[[1.000e+00, 1.110e+02, 2.210e+02, ..., 5.510e+02, 6.610e+02,
          7.710e+02],
         [8.810e+02, 9.910e+02, 1.101e+03, ..., 1.431e+03, 1.541e+03,
          1.651e+03],
         [1.761e+03, 1.871e+03, 1.981e+03, ..., 2.311e+03, 2.421e+03,
          2.531e+03],
         ...,
         [4.401e+03, 4.511e+03, 4.621e+03, ..., 4.951e+03, 5.061e+03,
          5.171e+03],
         [5.281e+03, 5.391e+03, 5.501e+03, ..., 5.831e+03, 5.941e+03,
          6.051e+03],
         [6.161e+03, 6.271e+03, 6.381e+03, ..., 6.711e+03, 6.821e+03,
          6.931e+03]],

        [[2.000e+00, 1.120e+02, 2.220e+02, ..., 5.520e+02, 6.620e+02,
          7.720e+02],
         [8.820e+02, 9.920e+02, 1.102e+03, ..., 1.432e+03, 1.542e+03,
          1.652e+03],
         [1.762e+03, 1.872e+03, 1.982e+03, ..., 2.312e+03, 2.422e+03,
          2.532e+03],
         ...,
         [4.402e+03, 4.512e+03, 4.622e+03, ..., 4.952e+03, 5.062e+03,
          5.172e+03],
         [5.282e+03, 5.392e+03, 5.502e+03, ..., 5.

In [ ]:
x1.shape

(1, 110, 64)

In [ ]:
x1 = x1.reshape(1, 110, 8, 8)

In [ ]:
x1.shape

(1, 110, 8, 8)

In [ ]:
x1.trans

AttributeError: 'numpy.ndarray' object has no attribute 'trans'

In [ ]:
x1.transpose(0, 2, 1, 3)

array([[[[1.000e+00, 1.110e+02, 2.210e+02, ..., 5.510e+02, 6.610e+02,
          7.710e+02],
         [2.000e+00, 1.120e+02, 2.220e+02, ..., 5.520e+02, 6.620e+02,
          7.720e+02],
         [3.000e+00, 1.130e+02, 2.230e+02, ..., 5.530e+02, 6.630e+02,
          7.730e+02],
         ...,
         [1.080e+02, 2.180e+02, 3.280e+02, ..., 6.580e+02, 7.680e+02,
          8.780e+02],
         [1.090e+02, 2.190e+02, 3.290e+02, ..., 6.590e+02, 7.690e+02,
          8.790e+02],
         [1.100e+02, 2.200e+02, 3.300e+02, ..., 6.600e+02, 7.700e+02,
          8.800e+02]],

        [[8.810e+02, 9.910e+02, 1.101e+03, ..., 1.431e+03, 1.541e+03,
          1.651e+03],
         [8.820e+02, 9.920e+02, 1.102e+03, ..., 1.432e+03, 1.542e+03,
          1.652e+03],
         [8.830e+02, 9.930e+02, 1.103e+03, ..., 1.433e+03, 1.543e+03,
          1.653e+03],
         ...,
         [9.880e+02, 1.098e+03, 1.208e+03, ..., 1.538e+03, 1.648e+03,
          1.758e+03],
         [9.890e+02, 1.099e+03, 1.209e+03, ..., 1.

In [ ]:
x1.shape

(1, 110, 8, 8)

In [ ]:
x1 = x1.transpose(0, 2, 1, 3)

In [ ]:
x1.shape

(1, 8, 110, 8)

In [ ]:
x1 = x1.transpose(0, 2, 1, 3)

In [ ]:
x1 = x1.reshape(1, 110, 64)

In [ ]:
x1.shape

(1, 110, 64)

In [ ]:
x1.transpose(0, 2, 1)

array([[[1.000e+00, 2.000e+00, 3.000e+00, ..., 1.080e+02, 1.090e+02,
         1.100e+02],
        [1.110e+02, 1.120e+02, 1.130e+02, ..., 2.180e+02, 2.190e+02,
         2.200e+02],
        [2.210e+02, 2.220e+02, 2.230e+02, ..., 3.280e+02, 3.290e+02,
         3.300e+02],
        ...,
        [6.711e+03, 6.712e+03, 6.713e+03, ..., 6.818e+03, 6.819e+03,
         6.820e+03],
        [6.821e+03, 6.822e+03, 6.823e+03, ..., 6.928e+03, 6.929e+03,
         6.930e+03],
        [6.931e+03, 6.932e+03, 6.933e+03, ..., 7.038e+03, 7.039e+03,
         7.040e+03]]])

In [ ]:
x1 = x1.transpose(0, 2, 1)

In [ ]:
x.shape

(1, 64, 10, 11)

In [ ]:
x1.rehsape(1, 64, 10, 11)

AttributeError: 'numpy.ndarray' object has no attribute 'rehsape'

In [ ]:
x1.shape

(1, 64, 110)

In [ ]:
x1.reshape(1, 64, 10, 11)

array([[[[1.000e+00, 2.000e+00, 3.000e+00, ..., 9.000e+00, 1.000e+01,
          1.100e+01],
         [1.200e+01, 1.300e+01, 1.400e+01, ..., 2.000e+01, 2.100e+01,
          2.200e+01],
         [2.300e+01, 2.400e+01, 2.500e+01, ..., 3.100e+01, 3.200e+01,
          3.300e+01],
         ...,
         [7.800e+01, 7.900e+01, 8.000e+01, ..., 8.600e+01, 8.700e+01,
          8.800e+01],
         [8.900e+01, 9.000e+01, 9.100e+01, ..., 9.700e+01, 9.800e+01,
          9.900e+01],
         [1.000e+02, 1.010e+02, 1.020e+02, ..., 1.080e+02, 1.090e+02,
          1.100e+02]],

        [[1.110e+02, 1.120e+02, 1.130e+02, ..., 1.190e+02, 1.200e+02,
          1.210e+02],
         [1.220e+02, 1.230e+02, 1.240e+02, ..., 1.300e+02, 1.310e+02,
          1.320e+02],
         [1.330e+02, 1.340e+02, 1.350e+02, ..., 1.410e+02, 1.420e+02,
          1.430e+02],
         ...,
         [1.880e+02, 1.890e+02, 1.900e+02, ..., 1.960e+02, 1.970e+02,
          1.980e+02],
         [1.990e+02, 2.000e+02, 2.010e+02, ..., 2.

In [ ]:
x1 == x

ValueError: operands could not be broadcast together with shapes (1,64,110) (1,64,10,11) 

In [ ]:
x.shape

(1, 64, 10, 11)

In [ ]:
x1.shape

(1, 64, 110)

In [ ]:
x1 = x1.reshape(1, 64, 10, 11)

In [ ]:
x1 == x

array([[[[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  T